version: '3.1'
services:
  backend:
    image: zadanie3_backend:md_backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: backend
    depends_on:
      - "database"

  frontend:
    image: zadanie3_frontend:md_frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - "database"

  database:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vavjs-eshop
    ports:
      - "5432:5432"
    container_name: database

  adminer:
    image: adminer
    restart: always
    ports:
      - 3030:8080
    depends_on:
      - "database"
    container_name: adminer